version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'basic-rest'
    ports:
      - 9011:9011
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'basic-rest'
      POSTGRES_PASSWORD: '123456'