server:
  port: ${SERVER_PORT:9011}

spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/basic-rest
    username: basic-rest
    password: 123456
  profiles:
    active: ${ACTIVE_PROFILE:default}
